routes:
  /signup/:
    template: members/signup
    data: page.signup
  /signin/:
    template: members/signin
    data: page.signin
  /membership/:
    template: members/membership
    data: page.membership
  /account/:
    template: members/account
    data: page.account
  /podcast/rss/:
    template: podcast/rss
    content_type: text/xml

collections:
  /:
    permalink: /{slug}/
    template: index
  /blog:
    permalink: /blog/{slug}/
    filter: tag:blog+tag:-podcast
  /podcast/:
    permalink: /podcast/{slug}/
    filter: tag:podcast+tag:-blog

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
