routes:
  /technologies/:
    controller: channel
    filter: author:yangyile+tag:Linux+tag:Nodejs+tag:Javascript+tag:Algorithm+tag:Framework+tag:Blog+tag:Web+tag:Security
    template: technologies
  /living/:
    controller: channel
    filter: author:yangyile+tag:Reading+tag:Photography+tag:Film+tag:Gongfu+tag:Car+tag:Finance+tag:Medicine+tag:Music
    template: living

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
