routes:
  /tags-technology/:
    controller: channel
    template: technologies
  /tags-living/:
    controller: channel
    template: living

collections:
  /blog/:
    permalink: /blog/{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
