routes:
  /technologies/:
    controller: channel
    template: technologies
  /living/:
    controller: channel
    template: living

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
