routes:
  /tags-technology/:
    controller: channel
    template: technologies
  /tags-living/:
    controller: channel
    template: living

collections:
  /:
    permalink: /{slug}/
    template: index
    order: updated_at desc

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
